# Generated by Django 5.2.4 on 2025-08-12 16:21

import news.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.utils.get_upload_path),
        ),
    ]
